export const SET_ENTRIES = "SET_ENTRIES";
export const UPDATE_ENTRY = "UPDATE_ENTRY";
export const DELETE_ENTRY = "DELETE_ENTRY";
export const SHOW_ENTRY = "SHOW_ENTRY";
export const SHOW_ENTRY_EDITOR = "SHOW_ENTRY_EDITOR";
export const SHOW_DELETE_ENTRY_MODAL = "SHOW_DELETE_ENTRY_MODAL";
export const CLOSE_DELETE_ENTRY_MODAL = "CLOSE_DELETE_ENTRY_MODAL";

export const SIGN_UP = "SIGN_UP";
export const SIGN_IN = "SIGN_IN";
export const RESUME_USER_SESSION = "RESUME_USER_SESSION";

export const UPDATE_SEARCH_QUERY = "UPDATE_SEARCH_QUERY";

export const SELECT_NOTIFICATION_ITEM = "SELECT_NOTIFICATION_ITEM";
export const SET_NOTIFICATION_ITEMS = "SET_NOTIFICATION_ITEMS";

export const GET_MERGE_REQUEST = "GET_MERGE_REQUEST";
export const ACCEPT_MERGE_REQUEST = "ACCEPT_MERGE_REQUEST";
export const REJECT_MERGE_REQUEST = "REJECT_MERGE_REQUEST";
